import type { Metadata } from "next";
import "./globals.css";
import GoogleProvider from "components/providers/GoogleProvider";

export const metadata: Metadata = {
  title: "IMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <GoogleProvider>
          {children}
        </GoogleProvider>
        {/* <li><Link href="/dashboard">Home</Link></li> */}


      </body>
    </html>
  );
}
